# Runtime settings for patient watcher
base_url: "http://115.241.194.20/LIS/Reports/Patient_Report.aspx/{id}"
check_every_sec: 30       # 10 minutes
timezone: "Asia/Kolkata"   # IANA timezone
patient_list_file: "patients.txt"
